import MainForm from "@/components/MainForm";
import { fetchFormById } from "@/lib/data";
import { Metadata } from "next";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function PublicFormIdPage({
  params: { id },
}: {
  params: { id: string };
}) {
  const form = await fetchFormById(id);

  if (!form?.id) {
    notFound();
  }

  return <MainForm form={form} publicForm />;
}

export default PublicFormIdPage;